<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * Todos direitos reservados para Thirdlevel | ThirdLevel All Rights Reserved
 *
 * @company   	ThirdLevel
 * @package    	MercadoLivre
 * @author      André Fuhrman (andrefuhrman@gmail.com)
 * @copyright  	Copyright (c) ThirdLevel [http://www.thirdlevel.com.br]
 * 
 */
?>

<div class="page-title">
<h1><?php echo Mage::helper('mercadolivre')->__('Domain Invalid'); ?></h1>
</div>
    <h3><?php echo Mage::helper('mercadolivre')->__('Sorry, the domain that you are using does not have license to use Thirdlevel MercadoLivre module'); ?></h3>

<br /><br />     
<a href="http://www.thirdlevel.com.br/magento/mercadolivre" target="_self"><?php echo Mage::helper('mercadolivre')->__('Click here to get more information and buy the module'); ?></a>






