<link href="<?php echo $this->getSkinUrl('unibanner/css/skitter.styles.css')?>" type="text/css" media="all" rel="stylesheet" />
<link href="<?php echo $this->getSkinUrl('unibanner/css/highlight.black.css')?>" type="text/css" media="all" rel="stylesheet" />
<link href="<?php echo $this->getSkinUrl('unibanner/css/sexy-bookmarks-style.css')?>" type="text/css" media="all" rel="stylesheet" />


<?php if( Mage::getStoreConfig('banner/banner/include_jquery', Mage::app()->getStore()) ): ?>
<script src="<?php echo $this->getSkinUrl('unibanner/js/jquery-1.8.2.min.js')?>"></script>
<script type="text/javascript">jQuery.noConflict()</script>
<?php endif ?>

<script src="<?php echo $this->getSkinUrl('unibanner/js/jquery.easing.1.3.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('unibanner/js/jquery.animate-colors-min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('unibanner/js/jquery.skitter.min.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('unibanner/js/highlight.js')?>"></script>
<script src="<?php echo $this->getSkinUrl('unibanner/js/sexy-bookmarks-public.js')?>"></script>